/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password.index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as EntriesEntryIdRouteImport } from './routes/entries.$entryId'
import { Route as AuthenticatedConfirmRouteImport } from './routes/_authenticated/_confirm'
import { Route as AuthenticatedConfirmEmailIndexRouteImport } from './routes/_authenticated/confirm-email.index'
import { Route as AuthenticatedConfirmEmailTokenRouteImport } from './routes/_authenticated/confirm-email.$token'
import { Route as AuthenticatedConfirmDashboardIndexRouteImport } from './routes/_authenticated/_confirm/dashboard.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesEntryIdRoute = EntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfirmRoute = AuthenticatedConfirmRouteImport.update({
  id: '/_confirm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfirmEmailIndexRoute =
  AuthenticatedConfirmEmailIndexRouteImport.update({
    id: '/confirm-email/',
    path: '/confirm-email/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfirmEmailTokenRoute =
  AuthenticatedConfirmEmailTokenRouteImport.update({
    id: '/confirm-email/$token',
    path: '/confirm-email/$token',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfirmDashboardIndexRoute =
  AuthenticatedConfirmDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedConfirmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/confirm-email/$token': typeof AuthenticatedConfirmEmailTokenRoute
  '/confirm-email': typeof AuthenticatedConfirmEmailIndexRoute
  '/dashboard': typeof AuthenticatedConfirmDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/confirm-email/$token': typeof AuthenticatedConfirmEmailTokenRoute
  '/confirm-email': typeof AuthenticatedConfirmEmailIndexRoute
  '/dashboard': typeof AuthenticatedConfirmDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_confirm': typeof AuthenticatedConfirmRouteWithChildren
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/_authenticated/confirm-email/$token': typeof AuthenticatedConfirmEmailTokenRoute
  '/_authenticated/confirm-email/': typeof AuthenticatedConfirmEmailIndexRoute
  '/_authenticated/_confirm/dashboard/': typeof AuthenticatedConfirmDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/entries/$entryId'
    | '/reset-password/$token'
    | '/reset-password'
    | '/confirm-email/$token'
    | '/confirm-email'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/entries/$entryId'
    | '/reset-password/$token'
    | '/reset-password'
    | '/confirm-email/$token'
    | '/confirm-email'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_confirm'
    | '/entries/$entryId'
    | '/reset-password/$token'
    | '/reset-password/'
    | '/_authenticated/confirm-email/$token'
    | '/_authenticated/confirm-email/'
    | '/_authenticated/_confirm/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EntriesEntryIdRoute: typeof EntriesEntryIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$entryId': {
      id: '/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof EntriesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_confirm': {
      id: '/_authenticated/_confirm'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedConfirmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/confirm-email/': {
      id: '/_authenticated/confirm-email/'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof AuthenticatedConfirmEmailIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/confirm-email/$token': {
      id: '/_authenticated/confirm-email/$token'
      path: '/confirm-email/$token'
      fullPath: '/confirm-email/$token'
      preLoaderRoute: typeof AuthenticatedConfirmEmailTokenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_confirm/dashboard/': {
      id: '/_authenticated/_confirm/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedConfirmDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedConfirmRoute
    }
  }
}

interface AuthenticatedConfirmRouteChildren {
  AuthenticatedConfirmDashboardIndexRoute: typeof AuthenticatedConfirmDashboardIndexRoute
}

const AuthenticatedConfirmRouteChildren: AuthenticatedConfirmRouteChildren = {
  AuthenticatedConfirmDashboardIndexRoute:
    AuthenticatedConfirmDashboardIndexRoute,
}

const AuthenticatedConfirmRouteWithChildren =
  AuthenticatedConfirmRoute._addFileChildren(AuthenticatedConfirmRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedConfirmRoute: typeof AuthenticatedConfirmRouteWithChildren
  AuthenticatedConfirmEmailTokenRoute: typeof AuthenticatedConfirmEmailTokenRoute
  AuthenticatedConfirmEmailIndexRoute: typeof AuthenticatedConfirmEmailIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfirmRoute: AuthenticatedConfirmRouteWithChildren,
  AuthenticatedConfirmEmailTokenRoute: AuthenticatedConfirmEmailTokenRoute,
  AuthenticatedConfirmEmailIndexRoute: AuthenticatedConfirmEmailIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EntriesEntryIdRoute: EntriesEntryIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
